/**
 * Example: Print images using both file paths and Buffers
 * Demonstrates the flexibility of the printImage/printToUSB functions
 */

import { readFile } from 'node:fs/promises';
import { printImage, printToUSB, getUSBPrinters } from './print.ts';

async function main() {
  try {
    console.log('🔍 Checking for printers...\n');
    const usbPrinters = await getUSBPrinters();

    if (usbPrinters.length === 0) {
      console.error('❌ No USB printers found');
      process.exit(1);
    }

    console.log(`✅ Found ${usbPrinters.length} USB printer(s):`);
    usbPrinters.forEach(p => console.log(`   - ${p.name}`));

    // Example 1: Print from file path (traditional way)
    console.log('\n📄 Example 1: Print from file path');
    const filePath = 'src/logo.png';

    const result1 = await printToUSB(filePath, {
      fitToPage: true,
      copies: 1
    });

    console.log(`✅ Job ${result1.jobId} sent to ${result1.printerName}`);

    // Example 2: Print from Buffer (useful for in-memory images)
    console.log('\n📄 Example 2: Print from Buffer');

    // Read image file into a buffer
    const imageBuffer = await readFile(filePath);
    console.log(`   Loaded ${imageBuffer.length} bytes into memory`);

    const result2 = await printToUSB(imageBuffer, {
      fitToPage: true,
      copies: 1,
      grayscale: true
    });

    console.log(`✅ Job ${result2.jobId} sent to ${result2.printerName}`);
    console.log('   (Printed directly from memory buffer!)');

    // Example 3: Print to a specific printer using Buffer
    console.log('\n📄 Example 3: Print to specific printer with Buffer');

    const firstPrinter = usbPrinters[0];
    const jobId = await printImage(firstPrinter.name, imageBuffer, {
      copies: 2,
      fitToPage: true
    });

    console.log(`✅ Job ${jobId} sent to ${firstPrinter.name} (2 copies)`);

    console.log('\n🎉 All examples completed!');
    console.log('\nBuffer printing is useful when:');
    console.log('  • Images are generated by AI or APIs');
    console.log('  • Processing images in memory');
    console.log('  • Avoiding temporary files');
    console.log('  • Printing multiple times from same data');

  } catch (error) {
    console.error('❌ Error:', error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}

main();

